baseurl = "https://huijzer.xyz"
title = "Huijzer.xyz"
theme = "speedy-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = ""

disableKinds = [
	"taxonomy",
	"taxonomyTerm"
]

# To avoid dropping HTML.
[markup.goldmark.renderer]
unsafe = true

[params]
    author = "Rik Huijzer"
    info = ""
    description = "Rik Huijzer's personal website"
    keywords = "blog,developer,personal"
    avatarurl = "img/self.jpg"

		# Might be an interesting option later.
    footercontent = ""

    hidecredits = true
    hidecopyright = true

    rtl = false

    math = true
    custom_css = []

# GDPR settings
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

# Menu links
[[menu.main]]
    name = "About"
    weight = 1
    url = "/about"
[[menu.main]]
    name = "Posts"
    weight = 1
    url  = "/posts"
