name: pages

on:
    push:
        branches:
            - 'master'

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v2
            - name: Install Nix
              uses: cachix/install-nix-action@v10
              with: 
                nix_path: nixpkgs=channel:nixos-20.03
            - name: Fetch Nix packages
              run: nix-shell --run "bash -c exit"
            - run: nix-shell --run "dvisvgm --help"
            - uses: julia-actions/setup-julia@latest 
              with:
                  version: 1.5
            - run: julia setup.jl
            - run: sudo apt install texlive-extra-utils 
            - run: julia -e 'import Site; Site.generate()'
            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                  hugo-version: '0.64.0'
                  extended: true
            - run: hugo --gc --minify
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./public

