name: pages

on:
    push:
        branches:
            - 'master'

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps: 
            - name: Git checkout
              uses: actions/checkout@v2

            - name: Install Julia
              uses: julia-actions/setup-julia@latest 
              with:
                  version: 1.5

            - name: Install Julia packages
              run: julia setup-packages.jl

            # Using the Nix package manager since the version of `dvisvgm` in Ubuntu is too old.
            - name: Install Nix
              uses: cachix/install-nix-action@v10
              with: 
                nix_path: nixpkgs=channel:nixos-20.03

            - name: Cache Nix store
              id: cache-nix-store
              uses: actions/cache@v2.1.0
              with:
                path: |
                  ~/nix/store
                  ~/nix/bin
                key: nix-${{ hashFiles('default.nix') }}

            - name: Install via Nix
              env: 
                CACHE_HIT: ${{ steps.cache-nix-store.outputs.cache-hit }}
              run: |
                NIX_BIN=/nix/var/nix/profiles/per-user/runner/profile/bin
                NIX_STORE=/nix/store
                if [[ "$CACHE_HIT" != 'true' ]]; then
                  nix-env --install
                  mkdir ~/nix
                  sudo cp --force --recursive $NIX_STORE/ ~/nix/store
                  sudo cp --force --recursive $NIX_BIN/ ~/nix/bin
                else
                  sudo mkdir --parents $NIX_STORE
                  sudo mkdir --parents $NIX_BIN
                  sudo cp --force --recursive ~/nix/store $NIX_STORE
                  sudo cp --force --recursive ~/nix/bin $NIX_BIN
                fi

            - name: Roughly summarize state
              run: ls src/posts > posts-list.txt

            - name: Cache LaTeX output
              uses: actions/cache@v2.1.0
              with:
                path: static/latex
                key: latex-${{ hashFiles('posts-list.txt') }}

            - name: Generate site with Julia
              run: julia -e 'import Site; Site.generate_and_time()'

            - name: Generate site with Hugo
              run: hugo --gc --minify

            - name: Deploy to secondary branch
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./public
                  cname: huijzer.xyz
