name: pages

on:
  schedule:
    - cron: '36 14 * * 6'
  push:
    branches:
    - 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
    - name: Git checkout
      uses: actions/checkout@v2

    # Using the Nix package manager since the version of `dvisvgm` in Ubuntu is too old.
    - name: Cache install Nix packages
      uses: nix-actions/cache-install@v1.0.6
      with: 
        key: nix-${{ hashFiles('default.nix') }}

    - name: Validate Nix install
      run: which dvisvgm

